"""add cv table

Revision ID: ab3729d34f0c
Revises: bfd9fddf3db7
Create Date: 2025-11-25 16:51:22.400709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3729d34f0c'
down_revision = 'bfd9fddf3db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_user_id'), 'cv', ['user_id'], unique=False)
    op.create_index(op.f('ix_cv_vacancy_id'), 'cv', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_vacancy_id'), table_name='cv')
    op.drop_index(op.f('ix_cv_user_id'), table_name='cv')
    op.drop_table('cv')
    # ### end Alembic commands ###